temperature: 0
max_tokens: 0
# Example: approximately based on the official specification minus 20k
max_context_window: 200000
base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
api_key: 
models:
  - openai/qwen-plus
figure_models:
  - google/Refer to the image generation models provided by Qwen
compressor_models:
  - openai/qwen-plus
read_figure_models:
  - openai/qwen-plus
